version: "3.7"
services:
  alarm-logger:
    build:
      context: ./alarm-logger
      dockerfile: Dockerfile
      args:
        - SUBSYSTEM=${SUBSYSTEM}     
    restart: always
    hostname: ${hostname}
    container_name: alarm-logger
    network_mode: host
    depends_on:
      - es
      - kibana
    environment:
      ES_PORT: 9202
      KAFKA_PORT: 29094
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.2
    restart: always
    container_name: elasticsearch
#    depends_on:
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - discovery.type=single-node
    ports:
      - 9202:9200
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.4
    restart: always 
    container_name: kibana
    ports:
        - "5602:5601"
    environment:
      SERVER_NAME: epics.logging.kibana
      ELASTICSEARCH_HOSTS: http://es:9200
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
